#!/bin/sh

[ $# -eq 1 ] || exec echo "usage: $0 <interface>"
[ -d "/sys/class/net/$1" ] || exec echo "$1: no such interface"

get_stats() {
	rx=$newrx
	tx=$newtx
	rxp=$newrxp
	txp=$newtxp
	read newrx <"/sys/class/net/$1/statistics/rx_bytes"
	read newtx <"/sys/class/net/$1/statistics/tx_bytes"
	read newrxp <"/sys/class/net/$1/statistics/rx_packets"
	read newtxp <"/sys/class/net/$1/statistics/tx_packets"
}

get_stats "$1"
while sleep 1 ; do
	get_stats "$1"
	printf 'rx: %u Mbps %u kpps tx: %u Mbps %u kpps\n' $(((newrx-rx) / 125000)) $(((newrxp-rxp) / 1000)) $(((newtx-tx) / 125000)) $(((newtxp-txp) / 1000))
done
